[west, -1, [
["CamoNet_BLUFOR_open_F", 0],
["CamoNet_BLUFOR_F", 0],
["CamoNet_BLUFOR_big_F", 0],
["CamoNet_wdl_open_F", 0],
["CamoNet_wdl_F", 0],
["CamoNet_wdl_big_F", 0],
["CamoNet_INDP_open_F", 0],
["CamoNet_INDP_F", 0],
["CamoNet_INDP_big_F", 0],
["CamoNet_ghex_open_F", 0],
["CamoNet_ghex_F", 0],
["CamoNet_ghex_big_F", 0],
["CamoNet_OPFOR_open_F", 0],
["CamoNet_OPFOR_F", 0],
["CamoNet_OPFOR_big_F", 0],
["Land_CamoNetVar_EAST_EP1", 0],
["Land_CamoNetB_EAST_EP1", 0],
["Land_CamoNetVar_NATO_EP1", 0],
["Land_CamoNetB_NATO_EP1", 0]
]] call acex_fortify_fnc_registerObjects;
