[west, -1, [
["Land_LampAirport_F", 0],
["Land_LampStreet_02_triple_F", 0],
["Land_LampHalogen_F", 0],
["Land_PortableLight_double_F", 0],
["TFAR_Land_Communication_F", 0],
["Land_Radar", 0],
["Land_WaterTower_01_F", 0],
["Land_vodni_vez", 0],
["PowGen_Big_EP1", 0],
["Land_PaperBox_open_full_F", 0],
["Land_PaperBox_01_open_water_F", 0],
["Land_PaperBox_closed_F", 0],
["Land_WaterBottle_01_stack_F", 0],
["Land_Pallet_MilBoxes_F", 0],
["Land_Pallets_stack_F", 0],
["Barrels", 0],
["Land_Pallets_F", 0],
["Land_PalletTrolley_01_khaki_F", 0],
["Land_GymRack_01_F", 0],
["Land_GymRack_02_F", 0],
["Land_GymBench_01_F", 0],
["Land_GymRack_03_F", 0],
["MetalBarrel_burning_F", 0],
["Land_MetalBarrel_F", 0]
]] call acex_fortify_fnc_registerObjects;
